### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by maclonghorn** [Mark-H/mhPayPal#2]
Loaded zip to packages and install local option doesn't see anything.  MODX 2.2.9-pl.

**Comment by Mark-H** [comment]
Note that it doesn't work if you download the entire repo as zip, you just need the transport.zip from the _packages directory. Going to assume you're not still waiting for an answer so will close this issue.

**Comment by maclonghorn** [comment]
ummm...3 years later for a response?  ;)  i've moved on.  yes, you may close it.

**Comment by Mark-H** [comment]
Sorry :D 

I don't recall seeing a notification about this issue. Something with too many projects on my name, and too little time, and this one isn't even formally released 😬
