### ISSUE TITLE
is this project dead or useable?

### ISSUE THREAD

**Issue by syberknight** [Mark-H/mhPayPal#3]
noticed it's 5 years old & blog post says it's not finished yet; worth the wait or move on? thanks!

**Comment by Mark-H** [comment]
Never noticed this issue until now, heh.

Technically I'd say it's neither dead nor usable, but unfinished. It's been running on my own site for donations for ages, and every now and then it seems to still work :P

**Comment by Mark-H** [comment]
It being on modx.com now should mean it's usable ;) That only took... 5,5 years lol https://modx.com/extras/package/mhpaypal
